apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    app: app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: api
          image: shalomberman/app-api:v1
          ports:
            - containerPort: 8000
              name: api