apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db
  labels:
    app: app-db
spec:
  serviceName: app-db-svc
  replicas: 2
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: db
          image: shalomberman/app-api:v1
          env:
          - name: USER
            value: user
          - name: PASSWORD
            value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: mysql-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
